definitions:
  steps:
    - step:
        name: &syntax-check
        image: atlassian/default-image:2
        script:
          - DEBIAN_FRONTEND=noninteractive apt-get update -y -qq && apt-get install -y -qq shellcheck xmlstarlet
          - sh -c "$(curl -ssL https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          - task syntax-check
        artifacts:
          - 'test-reports/**'
        condition:
          changesets:
            includePaths:
              - 'qrcode-wrapper/**/*.sh'
    - step:
        name: &lint
        image: hadolint/hadolint:latest-alpine
        script:
          - apk update && apk add --no-cache xmlstarlet
          - sh -c "$(wget -O - https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          - task lint
        artifacts:
          - 'test-reports/**'
        condition:
          changesets:
            includePaths:
              - qrcode-wrapper/Dockerfile
    - step:
        name: &build-image
        caches:
          - docker
        script:
          - echo TODO build docker image
        service:
          - docker
    - step:
        name: &dockle-scan
        caches:
          - docker
        script:
          - echo TODO dockle
        service:
          - docker
    - step:
        name: &test
        caches:
          - docker
        script:
          - echo TODO test
        service:
          - docker
    - step:
        name: &publish-image
        deployment: test
        caches:
          - docker
        script:
          - echo TODO publish-image
        service:
          - docker

pipelines:
  tags:
    '**':
      - parallel:
        - step: *syntax-check
        - step: *lint
      - step: *build-image
      - parallel:
        - step: *dockle-scan
        - step: *test
        - step: *publish-image
  pull-requests:
    '**':
      - parallel:
        - step: *syntax-check
        - step: *lint
      - parallel:
        - step: *dockle-scan
        - step: *test

  custom:
    renovate:
      - step:
          name: renovate
          image: renovate/renovate
          script:
            - git config --global user.email 'yujiorama+renovate-bot@gmail.com'
            - git config --global user.name 'Renovate Bot'
            - >
              renovate
              --platform bitbucket
              --username yujiorama
              --password $RENOVATE_PASSWORD
              --git-author "$(git config user.email)"
              --onboarding true
              --onboarding-config '{"extends":["config:base"]}'
              $BITBUCKET_REPO_FULL_NAME
