FROM golang:1.15-alpine

ARG HADOLINT_VERSION=1.19.0

RUN set -x \
 && apk add --no-cache shellcheck xmlstarlet curl git \
 && sh -c "$(curl -sSL https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin \
 && curl -fsSL -o /usr/local/bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64" \
 && chmod +x /usr/local/bin/hadolint

WORKDIR /app
COPY . /app
ENTRYPOINT ["/usr/local/bin/task"]
