version: 2.1

orbs:
  jira: circleci/jira@1.3.0

jobs:
  syntax-check:
    docker:
      - image: circleci/golang:1.15
    environment:
      SHELLCHECK: stable
    steps:
      - run:
          name: install taskfile
          command: >
            curl -fsSL --output - https://taskfile.dev/install.sh | sh -s -- -d -b ${HOME}/bin
      - run:
          name: install shellcheck
          command: >
            curl -fsSL --output - "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK}/shellcheck-${SHELLCHECK}.$(uname -s | tr A-Z a-z).$(uname -m).tar.xz" |
            tar -xJvf - --strip=1 --show-transformed-names -C ${HOME}/bin shellcheck-${SHELLCHECK}/shellcheck;
            chmod 755 ${HOME}/bin/shellcheck
      - run:
          name: install reviewdog
          command: >
            curl -fsSL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ${HOME}/bin
      - checkout
      - run:
          name: shellcheck
          command: >
            shellcheck --format=checkstyle ./qrcode-wrapper/*.sh |
            reviewdog
            -f="checkstyle"
            -name="shellcheck"
            -reporter="bitbucket-code-report"
            -filter-mode="nofilter"
            -fail-on-error="false"
            -level="warning"
  lint:
    docker:
      - image: circleci/golang:1.15
    environment:
      HADOLINT: 1.19.0
    steps:
      - run:
          name: install taskfile
          command: >
            curl -fsSL --output - https://taskfile.dev/install.sh | sh -s -- -d -b ${HOME}/bin
      - run:
          name: install hadolint
          command: |
            curl -fsSL --output ${HOME}/bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v${HADOLINT}/hadolint-$(uname -s | tr A-Z a-z)-$(uname -m)"
            chmod +x ${HOME}/bin/hadolint
      - run:
          name: install reviewdog
          command: >
            curl -fsSL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ${HOME}/bin
      - checkout
      - run:
          name: hadolint
          command: >
            hadolint --format=checkstyle --config .hadolint.yaml qrcode-wrapper/Dockerfile |
            reviewdog
            -f="checkstyle"
            -name="hadolint"
            -reporter="bitbucket-code-report"
            -filter-mode="nofilter"
            -fail-on-error="false"
            -level="warning"
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run: echo "hello"

workflows:
  check:
    jobs:
      - syntax-check
      - lint
      - build:
          post-steps:
            - jira/notify
