name: check
on:
  pull_request:
jobs:
  syntax-check:
    name: runner / suggester / syntax-check
    runs-on: ubuntu-latest
    steps:
      - name: install shellcheck(stable)
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get -qq -y && apt-get install -qq -y xmlstarlet
          curl -fsSL --output /var/tmp/shellcheck-stable.txz "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.$(uname -s | tr A-Z a-z).$(uname -m).tar.xz" | \
          tar -xJf /var/tmp/shellcheck-stable.txz -C /usr/local
          chmod 755 /usr/local/shellcheck-stable/shellcheck
          ln -s /usr/local/shellcheck-stable/shellcheck /usr/local/bin/shellcheck
          rm -f /var/tmp/shellcheck-stable.txz
      - uses: actions/checkout@v2
      - run: shellcheck --format=diff ./qrcode-wrapper/*.sh | patch -p1
      - name: suggester / shellcheck
        uses: ./
        with:
          tool_name: shellcheck

  lint:
    name: runner / suggester / lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - uses: ./qrcode-wrapper
      - uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: ${{ steps.reporter.outputs.value }}
          level: warning
