name: check
on:
  pull_request:
jobs:
  syntax-check:
    name: syntax-check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.5.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: ${{ steps.reporter.outputs.value }}
          level: warning
          path: qrcode-wrapper
          pattern: '*.sh'

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - name: install reviewdog
        uses: reviewdog/action-setup@v1
      - name: hadolint
        shell: bash
        env:
          INPUT_TOOL_NAME: hadolint
          INPUT_REPORTER: ${{ steps.reporter.outputs.value }}
          INPUT_LEVEL: warning
          INPUT_FILTER_MODE: added
          INPUT_FAIL_ON_ERROR: false
          INPUT_REVIEWDOG_FLAGS: ''
          REVIEWDOG_GITHUB_API_TOKEN: "${{ secrets.github_token }}"
          HADOLINT_VERSION: v1.19.0-alpine
          HADOLINT_CONFIG_PATH: .hadolint.yaml
          DOCKERFILE_PATH: qrcode-wrapper/Dockerfile
        run: >
          docker run --rm -i
          -v $(pwd)/${HADOLINT_CONFIG_PATH}:/.hadolint.yaml:ro
          -v $(pwd)/${DOCKERFILE_PATH}:/Dockerfile:ro
          hadolint/hadolint:${HADOLINT_VERSION}
          /bin/hadolint --config /.hadolint.yaml /Dockerfile |
          reviewdog -efm="%f:%l %m"
          -name="${INPUT_TOOL_NAME}"
          -reporter="${INPUT_REPORTER}"
          -filter-mode="${INPUT_FILTER_MODE}"
          -fail-on-error="${INPUT_FAIL_ON_ERROR}"
          -level="${INPUT_LEVEL}"
          "${INPUT_REVIEWDOG_FLAGS}"
